[tool.poetry]
name = "python-and-ia"
version = "0.1.0"
description = ""
authors = ["Angélica Rafaela <angelmaluh@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Django = "^5.0.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
